language: node_js
node_js:
  - 'stable'
addons:
  apt:
    packages:
      - sshpass
after_success:
  - export SSHPASS=$DEPLOY_PASS
  - test $TRAVIS_BRANCH = "master" && sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST -o stricthostkeychecking=no 'bash ./deploy_demo_master.sh'
