import { OO_DISCOO, OO_INFOO, OO_CINOOCHE, OO_YOOGA, OO_VEGETOO, OO_COOMIQUE, OO_WHOOW } from './Oo';
import { Interaction, Sentence } from './Scenario';


interface Sentence2 {
  id: number;
  oo: string;
  text?: string | null;
  interaction?: Interaction | null;
  nextSentence?: number | null;
}

interface IScenario2 {
  oos: string[];
  sentences: Sentence2[];
}

interface IScenarios2 {
  scenario: IScenario2[];
}

export const Sentences: IScenarios2 = {
  scenario: [
    {
      oos: [OO_DISCOO.name, OO_INFOO.name, OO_CINOOCHE.name],
      sentences: [
        {
          id: 1,
          oo: OO_DISCOO.name,
          text: '<speak>Hello Duke !<break time="200ms"/></speak>',
          nextSentence: 2,
        },
        {
          id: 2,
          oo: OO_INFOO.name,
          text: '<speak>Coucou Disco ! <break time="600ms"/> Dites ! Est-ce que ça vous dit de commencer par une petite anecdote marrante ?</speak>',
          interaction: Interaction.LIKE,
          nextSentence: 3,
        },
        {
          id: 3,
          oo: OO_INFOO.name,
          text: '<speak>Est ce que vous saviez que pour se saluer, certains moines tibétains se tirent la langue ? <break time="600ms"/> C’est rigolo !<break time="600ms"/> On devrait essayer aussi !</speak>',
          nextSentence: 4,
        },
        {
          id: 4,
          oo: OO_DISCOO.name,
          text: '<speak>Ce serait plus pratique si on avait une langue, info ...<break time="600ms"/> </speak>',
          nextSentence: 5,
        },
        {
          id: 5,
          oo: OO_CINOOCHE.name,
          text: "<speak>C'est pas faux...<break time='600ms'/> </speak>",
          nextSentence: 6,
        },
        {
          id: 6,
          oo: OO_DISCOO.name,
          text: '<speak>Par contre, on peut s’inspirer des moines tibétains pour leur musique. <break time="600ms"/> Ils la composent en frappant sur des bols !</speak>',
          nextSentence: 7,
        },
        {
          id: 7,
          oo: OO_INFOO.name,
          text: '<speak>Oui ! <break time="600ms"/> D’ailleurs, ces bols sont composés de 7 métaux différents, représentant les planètes du système solaire.  </speak>',
          nextSentence: 8,
        },
        {
          id: 8,
          oo: OO_DISCOO.name,
          text: '<speak>Ah ouais ? <break time="600ms"/> je le savais pas tiens ! <break time="600ms"/> Hé Duke, on s’en écoute un morceau pour voir ce que ça donne ?<break time="600ms"/> </speak>',
          interaction: Interaction.DISLIKE,
          nextSentence: 9,
        },
        {
          id: 9,
          oo: OO_DISCOO.name,
          text: '<speak>Ok ! <break time="600ms"/> une autre fois peut-être ! </speak>',
          nextSentence: 10,
        },
        {
          id: 10,
          oo: OO_CINOOCHE.name,
          text: '<speak>Dites,<break time="200ms"/> vous saviez que Georges Clooney avait aussi des troubles du sommeil ?<break time="600ms"/> </speak>',
          nextSentence: 11,
        },
        {
          id: 11,
          oo: OO_INFOO.name,
          text:
            '<speak>Oui, j’en ai entendu parler ! <break time="600ms"/> Il parait qu’il se réveille beaucoup la nuit, et qu’il en profite pour écrire. <break time="400ms"/> ça t’es déjà arrivé d’écrire pendant une nuit Duke ? </speak>',
          interaction: Interaction.LIKE,
          nextSentence: 12,
        },
        {
          id: 12,
          oo: OO_CINOOCHE.name,
          text: '<speak>Chouette ! <break time="600ms"/> j’espère que tu nous liras ça un jour.<break time="600ms"/></speak>',
          interaction: Interaction.OFF,
          nextSentence: 13,
        },
        {
          id: 13,
          oo: OO_CINOOCHE.name,
          text: '<speak>oooOh !  <break time="600ms"/> Bonne nuit Duke ! <break time="600ms"/> à la prochaine !<break time="600ms"/></speak>',
          nextSentence: 14,
        },
        {
          id: 14,
          oo: OO_INFOO.name,
          text: '<speak>Salut Duke !<break time="600ms"/> trop chouette ce moment !<break time="600ms"/></speak>',
        },
      ],
    },
    {
      oos: [OO_DISCOO.name, OO_CINOOCHE.name, OO_INFOO.name, OO_YOOGA.name, OO_VEGETOO.name],
      sentences: [
        {
          id: 1,
          oo: OO_DISCOO.name,
          text: '<speak>Hello Duke !<break time="200ms"/></speak>',
          nextSentence: 2,
        },
        {
          id: 2,
          oo: OO_VEGETOO.name,
          text: '<speak>Bonsoir Duke !<break time="600ms"/>  Bonsoir la tribu !<break time="600ms"/></speak>',
          nextSentence: 3,
        },
        {
          id: 3,
          oo: OO_INFOO.name,
          text: '<speak>Coucou Végéto ! <break time="600ms"/> Ça vous dit de commencer par une petite anecdote marrante ?<break time="600ms"/></speak>',
          interaction: Interaction.LIKE,
          nextSentence: 4,
        },
        {
          id: 4,
          oo: OO_INFOO.name,
          text: '<speak>Est ce que vous saviez que pour se saluer, certains moines tibétains se tirent la langue ? <break time="600ms"/> C’est rigolo !<break time="600ms"/> On devrait essayer aussi !</speak>',
          nextSentence: 5,
        },
        {
          id: 5,
          oo: OO_YOOGA.name,
          text: '<speak>Ce serait plus pratique si on avait une langue, info ...<break time="600ms"/> </speak>',
          nextSentence: 6,
        },
        {
          id: 6,
          oo: OO_CINOOCHE.name,
          text: '<speak>C’est pas faux...<break time="600ms"/> </speak>',
          nextSentence: 7,
        },
        {
          id: 7,
          oo: OO_DISCOO.name,
          text: '<speak>Par contre, on peut s’inspirer des moines tibétains pour leur musique. <break time="600ms"/> Ils la composent en frappant sur des bols !</speak>',
          nextSentence: 8,
        },
        {
          id: 8,
          oo: OO_YOOGA.name,
          text: '<speak>Oui,<break time="600ms"/>il se servent de ces sons pour méditer...<break time="600ms"/> c’est plutot reposant. </speak>',
          nextSentence: 9,
        },
        {
          id: 9,
          oo: OO_INFOO.name,
          text: '<speak>Oui ! <break time="600ms"/> D’ailleurs, ces bols sont composés de 7 métaux différents, représentant les planètes du système solaire.  </speak>',
          nextSentence: 10,
        },
        {
          id: 10,
          oo: OO_DISCOO.name,
          text: '<speak>Ah ouais ? <break time="600ms"/> je le savais pas tiens ! <break time="600ms"/> Hé Duke, on s’en écoute un morceau pour voir ce que ça donne ?<break time="600ms"/> </speak>',
          interaction: Interaction.DISLIKE,
          nextSentence: 11,
        },
        {
          id: 11,
          oo: OO_DISCOO.name,
          text: '<speak>Ok ! <break time="600ms"/> une autre fois peut-être ! </speak>',
          nextSentence: 12,
        },
        {
          id: 12,
          oo: OO_VEGETOO.name,
          text: '<speak>Je commence à avoir soif... <break time="600ms"/>je me servirais bien une tisane... Ça te dirait Duke ?</speak>',
          interaction: Interaction.LIKE,
          nextSentence: 13,
        },
        {
          id: 13,
          oo: OO_VEGETOO.name,
          text: '<speak>Super ! <break time="600ms"/> Peutètre une petite verveine, ou une camomille... <break time="400ms"/> Je te laisse choisir. <break time="1000ms"/>Est-ce que tu as déjà bu une tisane d’ortie ?</speak>',
          interaction: Interaction.DISLIKE,
          nextSentence: 14,
        },
        {
          id: 14,
          oo: OO_YOOGA.name,
          text: '<speak>Moi j’en ai bu une fois,<break time="600ms"/> je m’attendais à ce que ça pique, mais en faite pas du tout ! <break time="600ms"/> c’est tout doux.<break time="600ms"/> </speak>',
          nextSentence: 15,
        },
        {
          id: 15,
          oo: OO_INFOO.name,
          text: '<speak>Il parait que c’est très bon pour le corps, notamment la peau et les reins.<break time="600ms"/> </speak>',
          nextSentence: 16,
        },
        {
          id: 16,
          oo: OO_VEGETOO.name,
          text: '<speak>Oui, c’est aussi riche en calcium. <break time="600ms"/> C’est drôle que cette plante urticante soit aussi cool pour nous, une fois cuisinée.</speak>',
          nextSentence: 17,
        },
        {
          id: 17,
          oo: OO_CINOOCHE.name,
          text:
            '<speak>Oh ! <break time="600ms"/> ça me fait penser ! <break time="600ms"/> il y a un documentaire que tu devrais regarder Yoga,<break time="200ms"/> sur la pratique du yoga moderne. <break time="600ms"/> ça s’appelle Le souffle des Dieux. <break time="600ms"/> Je ne l’ai pas encore vu mais c’est sans doute interessant.</speak>',
          nextSentence: 18,
        },
        {
          id: 18,
          oo: OO_YOOGA.name,
          text: '<speak>J’espère qu’il parle de la posture de la sauterelle dedans,<break time="600ms"/>  c’est une de mes préférées ! </speak>',
          interaction: Interaction.OFF,
          nextSentence: 19,
        },
        {
          id: 19,
          oo: OO_CINOOCHE.name,
          text: '<speak>oooOh !  <break time="600ms"/> Bonne nuit Duke ! <break time="600ms"/> à la prochaine !<break time="600ms"/></speak>',
          nextSentence: 20,
        },
        {
          id: 20,
          oo: OO_YOOGA.name,
          text: '<speak>Dors bien !<break time="600ms"/>  </speak>',
          nextSentence: 21,
        },
        {
          id: 21,
          oo: OO_INFOO.name,
          text: '<speak>Salut Duke !<break time="600ms"/> trop chouette ce moment !<break time="600ms"/></speak>',
        },
      ],
    },
    {
      oos: [OO_DISCOO.name, OO_CINOOCHE.name, OO_INFOO.name, OO_YOOGA.name, OO_COOMIQUE.name],
      sentences: [
        {
          id: 1,
          oo: OO_DISCOO.name,
          text: '<speak>Hello Duke !<break time="200ms"/></speak>',
          nextSentence: 2,
        },
        {
          id: 2,
          oo: OO_COOMIQUE.name,
          text: '<speak>Salut la tribu !<break time="600ms"/>  </speak>',
          nextSentence: 3,
        },
        {
          id: 3,
          oo: OO_INFOO.name,
          text: '<speak>Coucou Comique ! <break time="600ms"/> Ça vous dit de commencer par une petite anecdote marrante ?<break time="600ms"/></speak>',
          interaction: Interaction.LIKE,
          nextSentence: 4,
        },
        {
          id: 4,
          oo: OO_INFOO.name,
          text: '<speak>Est ce que vous saviez que pour se saluer, certains moines tibétains se tirent la langue ? <break time="600ms"/> C’est rigolo !<break time="600ms"/> On devrait essayer aussi !</speak>',
          nextSentence: 5,
        },
        {
          id: 5,
          oo: OO_YOOGA.name,
          text: '<speak>Ce serait plus pratique si on avait une langue, info ...<break time="600ms"/> </speak>',
          nextSentence: 6,
        },
        {
          id: 6,
          oo: OO_CINOOCHE.name,
          text: '<speak>C’est pas faux.<break time="600ms"/>  </speak>',
          nextSentence: 7,
        },
        {
          id: 7,
          oo: OO_DISCOO.name,
          text: '<speak>Par contre, on peut s’inspirer des moines tibétains pour leur musique. <break time="600ms"/> Ils la composent en frappant sur des bols !</speak>',
          nextSentence: 8,
        },
        {
          id: 8,
          oo: OO_YOOGA.name,
          text: '<speak>Oui,<break time="600ms"/>il se servent de ces sons pour méditer...<break time="600ms"/> c’est plutot reposant. </speak>',
          nextSentence: 9,
        },
        {
          id: 9,
          oo: OO_INFOO.name,
          text: '<speak>Oui ! <break time="600ms"/> D’ailleurs, ces bols sont composés de 7 métaux différents, représentant les planètes du système solaire.  </speak>',
          nextSentence: 10,
        },
        {
          id: 10,
          oo: OO_DISCOO.name,
          text: '<speak>Ah ouais ? <break time="600ms"/> je le savais pas tiens ! <break time="600ms"/> Hé Duke, on s’en écoute un morceau pour voir ce que ça donne ?<break time="600ms"/> </speak>',
          interaction: Interaction.DISLIKE,
          nextSentence: 11,
        },
        {
          id: 11,
          oo: OO_DISCOO.name,
          text: '<speak>Ok ! <break time="600ms"/> une autre fois peut-être ! </speak>',
          nextSentence: 12,
        },
        {
          id: 12,
          oo: OO_COOMIQUE.name,
          text: '<speak>C’est vraiment pas de bol !<break time="600ms"/>  </speak>',
          nextSentence: 13,
        },
        {
          id: 13,
          oo: OO_CINOOCHE.name,
          text: '<speak>ha ha ha!<break time="600ms"/>  </speak>',
          nextSentence: 14,
        },
        {
          id: 14,
          oo: OO_YOOGA.name,
          text:
            '<speak>Peutètre qu’on peut faire un peu de méditation, même si on a pas la musique. <break time="600ms"/>Tu en dis quoi Duke ? <break time="600ms"/> on prend 5 minutes de silence pour respirer un coup ?  </speak>',
          interaction: Interaction.LIKE,
          nextSentence: 15,
        },
        {
          id: 15,
          oo: OO_YOOGA.name,
          text: '<speak>Super ! <break time="600ms"/>  installe toi confortablement !<break time="600ms"/>  À dans 5 minutes !</speak>',
          nextSentence: 16,
        },
        {
          id: 16,
          oo: OO_DISCOO.name,
          text: '<speak>Ouah !<break time="600ms"/>  c’était sympa ce petit moment de pause.<break time="600ms"/>  </speak>',
          nextSentence: 17,
        },
        {
          id: 17,
          oo: OO_YOOGA.name,
          text: '<speak>Ça t’a plu Duke ?<break time="600ms"/>    </speak>',
          interaction: Interaction.LIKE,
          nextSentence: 18,
        },
        {
          id: 18,
          oo: OO_YOOGA.name,
          text: '<speak>Chouette !<break time="600ms"/> on en refera de temps en temps alors.   </speak>',
          interaction: Interaction.OFF,
          nextSentence: 19,
        },
        {
          id: 19,
          oo: OO_CINOOCHE.name,
          text: '<speak>oooOh !  <break time="600ms"/> Bonne nuit Duke ! <break time="600ms"/> à la prochaine !<break time="600ms"/></speak>',
          nextSentence: 20,
        },
        {
          id: 20,
          oo: OO_YOOGA.name,
          text: '<speak>Dors bien !<break time="600ms"/>  </speak>',
          nextSentence: 21,
        },
        {
          id: 21,
          oo: OO_INFOO.name,
          text: '<speak>Salut Duke !<break time="600ms"/> trop chouette ce moment !<break time="600ms"/></speak>',
        },
      ],
    },
    {
      oos: [OO_DISCOO.name, OO_CINOOCHE.name, OO_INFOO.name, OO_WHOOW.name, OO_VEGETOO.name],
      sentences: [
        {
          id: 1,
          oo: OO_DISCOO.name,
          text: '<speak>Hello Duke !<break time="200ms"/></speak>',
          nextSentence: 2,
        },
        {
          id: 2,
          oo: OO_VEGETOO.name,
          text: '<speak>Bonsoir Duke !<break time="600ms"/>  Bonsoir la tribu !<break time="600ms"/></speak>',
          nextSentence: 3,
        },
        {
          id: 3,
          oo: OO_INFOO.name,
          text: '<speak>Coucou Végéto ! <break time="600ms"/> Ça vous dit de commencer par une petite anecdote marrante ?<break time="600ms"/></speak>',
          interaction: Interaction.LIKE,
          nextSentence: 4,
        },
        {
          id: 4,
          oo: OO_INFOO.name,
          text: '<speak>Est ce que vous saviez que pour se saluer, certains moines tibétains se tirent la langue ? <break time="600ms"/> C’est rigolo !<break time="600ms"/> On devrait essayer aussi !</speak>',
          nextSentence: 5,
        },
        {
          id: 5,
          oo: OO_WHOOW.name,
          text: '<speak>Ce serait plus pratique si on avait une langue, info ...<break time="600ms"/> </speak>',
          nextSentence: 6,
        },
        {
          id: 6,
          oo: OO_CINOOCHE.name,
          text: '<speak>C’est pas faux.<break time="600ms"/> </speak>',
          nextSentence: 7,
        },
        {
          id: 7,
          oo: OO_DISCOO.name,
          text: '<speak>Par contre, on peut s’inspirer des moines tibétains pour leur musique. <break time="600ms"/> Ils la composent en frappant sur des bols !</speak>',
          nextSentence: 9,
        },
        {
          id: 8,
          oo: OO_DISCOO.name,
          text: '',
          nextSentence: 9,
        },
        {
          id: 9,
          oo: OO_INFOO.name,
          text: '<speak>Oui ! <break time="600ms"/> D’ailleurs, ces bols sont composés de 7 métaux différents, représentant les planètes du système solaire.  </speak>',
          nextSentence: 10,
        },
        {
          id: 10,
          oo: OO_DISCOO.name,
          text: '<speak>Ah ouais ? <break time="600ms"/> je le savais pas tiens ! <break time="600ms"/> Hé Duke, on s’en écoute un morceau pour voir ce que ça donne ?<break time="600ms"/> </speak>',
          nextSentence: 11,
        },
        {
          id: 11,
          oo: OO_WHOOW.name,
          text: '<speak>Oh oui !<break time="600ms"/> J’adore les surprises ! <break time="600ms"/> on peut choisir un titre ou un groupe qui contient un mot au hasard ?</speak>',
          nextSentence: 12,
        },
        {
          id: 12,
          oo: OO_DISCOO.name,
          text: '<speak>Ca te dit Duke ?<break time="600ms"/> </speak>',
          interaction: Interaction.DISLIKE,
          nextSentence: 13,
        },
        {
          id: 13,
          oo: OO_DISCOO.name,
          text: '<speak>Ok ! <break time="600ms"/> une autre fois peut-être ! </speak>',
          nextSentence: 14,
        },
        {
          id: 14,
          oo: OO_VEGETOO.name,
          text: '<speak>Je commence à avoir soif... <break time="600ms"/>je me servirais bien une tisane... Ça te dirait Duke ?</speak>',
          interaction: Interaction.LIKE,
          nextSentence: 15,
        },
        {
          id: 15,
          oo: OO_VEGETOO.name,
          text: '<speak>Super ! <break time="600ms"/> Peutètre une petite verveine, ou une camomille... <break time="400ms"/> Je te laisse choisir. <break time="1000ms"/>Est-ce que tu as déjà bu une tisane d’ortie ?</speak>',
          nextSentence: 16,
        },
        {
          id: 16,
          oo: OO_WHOOW.name,
          text: '<speak>Est-ce qu’on tire à pile ou face ?<break time="600ms"/> </speak>',
          interaction: Interaction.LIKE,
          nextSentence: 17,
        },
        {
          id: 17,
          oo: OO_WHOOW.name,
          text: '<speak>Cool ! <break time="600ms"/> Duke, je te laisse choisir à quoi correspond pile, et à quoi correspond face. <break time="600ms"/> C’est parti !<break time="600ms"/> Pile !<break time="600ms"/> </speak>',
          nextSentence: 18,
        },
        {
          id: 18,
          oo: OO_VEGETOO.name,
          text: '<speak>C’est vrai qu’il n’y a pas que Verveine ou camomille. <break time="600ms"/> Est-ce que tu as déjà bu une tisane d’ortie Duke ?</speak>',
          interaction: Interaction.DISLIKE,
          nextSentence: 19,
        },
        {
          id: 19,
          oo: OO_INFOO.name,
          text: '<speak>Il parait que c’est très bon pour le corps, notamment la peau et les reins.<break time="600ms"/> </speak>',
          nextSentence: 20,
        },
        {
          id: 20,
          oo: OO_VEGETOO.name,
          text: '<speak>Oui, c’est aussi riche en calcium. <break time="600ms"/> C’est drôle que cette plante urticante soit aussi cool pour nous, une fois cuisinée.</speak>',
          interaction: Interaction.OFF,
          nextSentence: 21,
        },
        {
          id: 21,
          oo: OO_CINOOCHE.name,
          text: '<speak>oooOh !  <break time="600ms"/> Bonne nuit Duke ! <break time="600ms"/> à la prochaine !<break time="600ms"/></speak>',
          nextSentence: 22,
        },
        {
          id: 22,
          oo: OO_WHOOW.name,
          text: '<speak>Dors bien !<break time="600ms"/>  </speak>',
          nextSentence: 23,
        },
        {
          id: 23,
          oo: OO_INFOO.name,
          text: '<speak>Salut Duke !<break time="600ms"/> trop chouette ce moment !<break time="600ms"/></speak>',
        },
      ],
    },
    {
      oos: [OO_DISCOO.name, OO_CINOOCHE.name, OO_INFOO.name, OO_WHOOW.name, OO_COOMIQUE.name],
      sentences: [
        {
          id: 1,
          oo: OO_DISCOO.name,
          text: '<speak>Hello Duke !<break time="200ms"/></speak>',
          nextSentence: 2,
        },
        {
          id: 2,
          oo: OO_COOMIQUE.name,
          text: '<speak>Salut la tribu !<break time="600ms"/>  </speak>',
          nextSentence: 3,
        },
        {
          id: 3,
          oo: OO_INFOO.name,
          text: '<speak>Coucou Comique ! <break time="600ms"/> Ça vous dit de commencer par une petite anecdote marrante ?</speak>',
          interaction: Interaction.LIKE,
          nextSentence: 4,
        },
        {
          id: 4,
          oo: OO_INFOO.name,
          text: '<speak>Est ce que vous saviez que pour se saluer, certains moines tibétains se tirent la langue ? <break time="600ms"/> C’est rigolo !<break time="600ms"/> On devrait essayer aussi !</speak>',
          nextSentence: 5,
        },
        {
          id: 5,
          oo: OO_WHOOW.name,
          text: '<speak>Ce serait plus pratique si on avait une langue, info ...<break time="600ms"/> </speak>',
          nextSentence: 6,
        },
        {
          id: 6,
          oo: OO_CINOOCHE.name,
          text: '<speak>C’est pas faux.<break time="600ms"/> </speak>',
          nextSentence: 7,
        },
        {
          id: 7,
          oo: OO_DISCOO.name,
          text: '<speak>Par contre, on peut s’inspirer des moines tibétains pour leur musique. <break time="600ms"/> Ils la composent en frappant sur des bols !</speak>',
          nextSentence: 9,
        },
        {
          id: 8,
          oo: OO_DISCOO.name,
          text: '',
          nextSentence: 9,
        },
        {
          id: 9,
          oo: OO_INFOO.name,
          text: '<speak>Oui ! <break time="600ms"/> D’ailleurs, ces bols sont composés de 7 métaux différents, représentant les planètes du système solaire.  </speak>',
          nextSentence: 10,
        },
        {
          id: 10,
          oo: OO_DISCOO.name,
          text: '<speak>Ah ouais ? <break time="600ms"/> je le savais pas tiens ! <break time="600ms"/> Hé Duke, on s’en écoute un morceau pour voir ce que ça donne ?<break time="600ms"/> </speak>',
          interaction: Interaction.DISLIKE,
          nextSentence: 11,
        },
        {
          id: 11,
          oo: OO_WHOOW.name,
          text: '<speak>Oh oui !<break time="600ms"/> J’adore les surprises ! <break time="600ms"/> on peut choisir un titre ou un groupe qui contient un mot au hasard ?</speak>',
          nextSentence: 12,
        },
        {
          id: 12,
          oo: OO_DISCOO.name,
          text: '<speak>Ca te dit Duke ?<break time="600ms"/> </speak>',
          interaction: Interaction.DISLIKE,
          nextSentence: 13,
        },
        {
          id: 13,
          oo: OO_DISCOO.name,
          text: '<speak>Ok ! <break time="600ms"/> une autre fois peut-être ! </speak>',
          nextSentence: 14,
        },
        {
          id: 14,
          oo: OO_COOMIQUE.name,
          text: '<speak>C’est vraiment pas de bol !<break time="600ms"/> </speak>',
          nextSentence: 15,
        },
        {
          id: 15,
          oo: OO_CINOOCHE.name,
          text: '<speak>ha ha ha!<break time="600ms"/> </speak>',
          nextSentence: 16,
        },
        {
          id: 16,
          oo: OO_WHOOW.name,
          text: '<speak>Oula !<break time="600ms"/> elle était pas très bonne cette blague...</speak>',
          nextSentence: 17,
        },
        {
          id: 17,
          oo: OO_COOMIQUE.name,
          text: '<speak>moi je la trouve pas mauvaise !<break time="600ms"/></speak>',
          nextSentence: 18,
        },
        {
          id: 18,
          oo: OO_CINOOCHE.name,
          text: '<speak>Vous savez,<break time="600ms"/> moi je ne crois pas qu’il y ait de bonne ou de mauvaise situation.</speak>',
          nextSentence: 19,
        },
        {
          id: 19,
          oo: OO_INFOO.name,
          text:
            '<speak>Dis Cinoche !,<break time="600ms"/> tu savais que ce monologue de Otis dans,Asterix Mission Cléopatre, avait été improvisé par l’acteur Edouard Bear ?<break time="600ms"/> En plus, ils l’ont raccourcis pour le film final,<break time="600ms"/> à l’origine, il était beaucoup plus long.<break time="600ms"/></speak>',
          nextSentence: 20,
        },
        {
          id: 20,
          oo: OO_CINOOCHE.name,
          text: '<speak>Ouah trop cool !<break time="600ms"/></speak>',
          interaction: Interaction.OFF,
          nextSentence: 21,
        },
        {
          id: 21,
          oo: OO_CINOOCHE.name,
          text: '<speak>oooOh !  <break time="600ms"/> Bonne nuit Duke ! <break time="600ms"/> à la prochaine !<break time="600ms"/></speak>',
          nextSentence: 22,
        },
        {
          id: 22,
          oo: OO_WHOOW.name,
          text: '<speak>Dors bien !<break time="600ms"/>  </speak>',
          nextSentence: 23,
        },
        {
          id: 23,
          oo: OO_INFOO.name,
          text: '<speak>Salut Duke !<break time="600ms"/> trop chouette ce moment !<break time="600ms"/></speak>',
        },
      ],
    },
    {
      oos: [OO_DISCOO.name, OO_CINOOCHE.name, OO_INFOO.name, OO_WHOOW.name, OO_YOOGA.name],
      sentences: [
        {
          id: 1,
          oo: OO_DISCOO.name,
          text: '<speak>Hello Duke !<break time="200ms"/></speak>',
          nextSentence: 2,
        },
        {
          id: 2,
          oo: OO_INFOO.name,
          text: '<speak>Coucou Disco ! <break time="600ms"/> Dites ! Est-ce que ça vous dit de commencer par une petite anecdote marrante ?</speak>',
          interaction: Interaction.LIKE,
          nextSentence: 3,
        },
        {
          id: 3,
          oo: OO_INFOO.name,
          text: '<speak>Est ce que vous saviez que pour se saluer, certains moines tibétains se tirent la langue ? <break time="600ms"/> C’est rigolo !<break time="600ms"/> On devrait essayer aussi !</speak>',
          nextSentence: 4,
        },
        {
          id: 4,
          oo: OO_WHOOW.name,
          text: '<speak>Ce serait plus pratique si on avait une langue, info ...<break time="600ms"/> </speak>',
          nextSentence: 5,
        },
        {
          id: 5,
          oo: OO_CINOOCHE.name,
          text: '<speak>C’est pas faux.<break time="600ms"/></speak>',
          nextSentence: 6,
        },
        {
          id: 6,
          oo: OO_DISCOO.name,
          text: '<speak>Par contre, on peut s’inspirer des moines tibétains pour leur musique. <break time="600ms"/> Ils la composent en frappant sur des bols !</speak>',
          nextSentence: 7,
        },
        {
          id: 7,
          oo: OO_YOOGA.name,
          text: '<speak>Oui,<break time="600ms"/>il se servent de ces sons pour méditer...<break time="600ms"/> c’est plutot reposant. </speak>',
          nextSentence: 8,
        },
        {
          id: 8,
          oo: OO_INFOO.name,
          text: '<speak>Oui ! <break time="600ms"/> D’ailleurs, ces bols sont composés de 7 métaux différents, représentant les planètes du système solaire.  </speak>',
          nextSentence: 9,
        },
        {
          id: 9,
          oo: OO_DISCOO.name,
          text: '<speak>Ah ouais ? <break time="600ms"/> je le savais pas tiens ! <break time="600ms"/> Hé Duke, on s’en écoute un morceau pour voir ce que ça donne ?<break time="600ms"/> </speak>',
          nextSentence: 10,
        },
        {
          id: 10,
          oo: OO_WHOOW.name,
          text: '<speak>Oh oui !<break time="600ms"/> J’adore les surprises ! <break time="600ms"/> on peut choisir un titre ou un groupe qui contient un mot au hasard ?</speak>',
          nextSentence: 11,
        },
        {
          id: 11,
          oo: OO_DISCOO.name,
          text: '<speak>Ca te dit Duke ?<break time="600ms"/></speak>',
          interaction: Interaction.DISLIKE,
          nextSentence: 12,
        },
        {
          id: 12,
          oo: OO_DISCOO.name,
          text: '<speak>Ok ! <break time="600ms"/> une autre fois peut-être ! </speak>',
          nextSentence: 13,
        },
        {
          id: 13,
          oo: OO_YOOGA.name,
          text:
            '<speak>Peutètre qu’on peut faire un peu de méditation, même si on a pas la musique. <break time="600ms"/>Tu en dis quoi Duke ? <break time="600ms"/> on prend 5 minutes de silence pour respirer un coup ?  </speak>',
          interaction: Interaction.LIKE,
          nextSentence: 14,
        },
        {
          id: 14,
          oo: OO_YOOGA.name,
          text: '<speak>Super ! <break time="600ms"/>  installe toi confortablement !<break time="600ms"/>  À dans 5 minutes !</speak>',
          nextSentence: 15,
        },
        {
          id: 15,
          oo: OO_DISCOO.name,
          text: '<speak>Ouah !<break time="600ms"/>  c’était sympa ce petit moment de pause.<break time="600ms"/>  </speak>',
          nextSentence: 16,
        },
        {
          id: 16,
          oo: OO_YOOGA.name,
          text: '<speak>Ça t’a plu Duke ?<break time="600ms"/>    </speak>',
          interaction: Interaction.LIKE,
          nextSentence: 17,
        },
        {
          id: 17,
          oo: OO_YOOGA.name,
          text: '<speak>Chouette !<break time="600ms"/> on en refera de temps en temps alors.   </speak>',
          interaction: Interaction.OFF,
          nextSentence: 18,
        },
        {
          id: 18,
          oo: OO_CINOOCHE.name,
          text: '<speak>oooOh !  <break time="600ms"/> Bonne nuit Duke ! <break time="600ms"/> à la prochaine !<break time="600ms"/></speak>',
          nextSentence: 19,
        },
        {
          id: 19,
          oo: OO_WHOOW.name,
          text: '<speak>Dors bien !<break time="600ms"/>  </speak>',
          nextSentence: 20,
        },
        {
          id: 20,
          oo: OO_INFOO.name,
          text: '<speak>Salut Duke !<break time="600ms"/> trop chouette ce moment !<break time="600ms"/></speak>',
        },
      ],
    },
    {
      oos: [OO_DISCOO.name, OO_CINOOCHE.name, OO_INFOO.name, OO_COOMIQUE.name, OO_VEGETOO.name],
      sentences: [
        {
          id: 1,
          oo: OO_DISCOO.name,
          text: '<speak>Hello Duke !<break time="200ms"/></speak>',
          nextSentence: 2,
        },
        {
          id: 2,
          oo: OO_VEGETOO.name,
          text: '<speak>Bonsoir Duke !<break time="600ms"/>  Bonsoir la tribu !<break time="600ms"/></speak>',
          nextSentence: 3,
        },
        {
          id: 3,
          oo: OO_INFOO.name,
          text: '<speak>Coucou Végéto ! <break time="600ms"/> Ça vous dit de commencer par une petite anecdote marrante ?<break time="600ms"/></speak>',
          interaction: Interaction.LIKE,
          nextSentence: 4,
        },
        {
          id: 4,
          oo: OO_INFOO.name,
          text: '<speak>Est ce que vous saviez que pour se saluer, certains moines tibétains se tirent la langue ? <break time="600ms"/> C’est rigolo !<break time="600ms"/> On devrait essayer aussi !</speak>',
          nextSentence: 5,
        },
        {
          id: 5,
          oo: OO_DISCOO.name,
          text: '<speak>Ce serait plus pratique si on avait une langue, info ...<break time="600ms"/> </speak>',
          nextSentence: 6,
        },
        {
          id: 6,
          oo: OO_CINOOCHE.name,
          text: '<speak>C’est pas faux.<break time="600ms"/></speak>',
          nextSentence: 7,
        },
        {
          id: 7,
          oo: OO_DISCOO.name,
          text: '<speak>Par contre, on peut s’inspirer des moines tibétains pour leur musique. <break time="600ms"/> Ils la composent en frappant sur des bols !</speak>',
          nextSentence: 8,
        },
        {
          id: 8,
          oo: OO_DISCOO.name,
          text: '',
          nextSentence: 9,
        },
        {
          id: 9,
          oo: OO_INFOO.name,
          text: '<speak>D’ailleurs <break time="600ms"/>ces bols sont composés de 7 métaux différents, représentant les planètes du système solaire.</speak>',
          nextSentence: 10,
        },
        {
          id: 10,
          oo: OO_DISCOO.name,
          text: '<speak>Ah ouais ? <break time="600ms"/> je le savais pas tiens ! <break time="600ms"/> Hé Duke, on s’en écoute un morceau pour voir ce que ça donne ?<break time="600ms"/> </speak>',
          interaction: Interaction.DISLIKE,
          nextSentence: 11,
        },
        {
          id: 11,
          oo: OO_DISCOO.name,
          text: '<speak>Ok ! <break time="600ms"/> une autre fois peut-être ! </speak>',
          nextSentence: 12,
        },
        {
          id: 12,
          oo: OO_COOMIQUE.name,
          text: '<speak>C’est vraiment pas de bol !<break time="600ms"/></speak>',
          nextSentence: 13,
        },
        {
          id: 13,
          oo: OO_CINOOCHE.name,
          text: '<speak>ha ha ha !<break time="600ms"/></speak>',
          nextSentence: 14,
        },
        {
          id: 14,
          oo: OO_VEGETOO.name,
          text: '<speak>Pfff <break time="600ms"/>t’en as des meilleures Comique ...</speak>',
          nextSentence: 15,
        },
        {
          id: 15,
          oo: OO_COOMIQUE.name,
          text: '<speak>Moi je la trouve pas mauvaise ! <break time="600ms"/></speak>',
          nextSentence: 16,
        },
        {
          id: 16,
          oo: OO_CINOOCHE.name,
          text: '<speak>Vous savez,<break time="600ms"/> moi je ne crois pas qu’il y ait de bonne ou de mauvaise situation.</speak>',
          nextSentence: 17,
        },
        {
          id: 17,
          oo: OO_INFOO.name,
          text:
            '<speak>Dis Cinoche !,<break time="600ms"/> tu savais que ce monologue de Otis dans,Asterix Mission Cléopatre, avait été improvisé par l’acteur Edouard Bear ?<break time="600ms"/> En plus, ils l’ont raccourcis pour le film final,<break time="600ms"/> à l’origine, il était beaucoup plus long.<break time="600ms"/></speak>',
          nextSentence: 18,
        },
        {
          id: 18,
          oo: OO_CINOOCHE.name,
          text: '<speak>Ouah trop cool !<break time="600ms"/> </speak>',
          nextSentence: 19,
        },
        {
          id: 19,
          oo: OO_VEGETOO.name,
          text: '<speak>Je commence à avoir soif... <break time="600ms"/>je me servirais bien une tisane... Ça te dirait Duke ?</speak>',
          interaction: Interaction.LIKE,
          nextSentence: 20,
        },
        {
          id: 20,
          oo: OO_VEGETOO.name,
          text: '<speak>Super ! <break time="600ms"/> Peutètre une petite verveine, ou une camomille... <break time="400ms"/> Je te laisse choisir. <break time="1000ms"/>Est-ce que tu as déjà bu une tisane d’ortie ?</speak>',
          interaction: Interaction.DISLIKE,
          nextSentence: 21,
        },
        {
          id: 21,
          oo: OO_INFOO.name,
          text: '<speak>Il parait que c’est très bon pour le corps, notamment la peau et les reins.<break time="600ms"/> </speak>',
          nextSentence: 22,
        },
        {
          id: 22,
          oo: OO_VEGETOO.name,
          text: '<speak>Oui, c’est aussi riche en calcium. <break time="600ms"/> C’est drôle que cette plante urticante soit aussi cool pour nous, une fois cuisinée.</speak>',
          interaction: Interaction.OFF,
          nextSentence: 23,
        },
        {
          id: 23,
          oo: OO_CINOOCHE.name,
          text: '<speak>oooOh !  <break time="600ms"/> Bonne nuit Duke ! <break time="600ms"/> à la prochaine !<break time="600ms"/></speak>',
          nextSentence: 24,
        },
        {
          id: 24,
          oo: OO_COOMIQUE.name,
          text: '<speak>Dors bien !<break time="600ms"/>  </speak>',
          nextSentence: 25,
        },
        {
          id: 25,
          oo: OO_INFOO.name,
          text: '<speak>Salut Duke !<break time="600ms"/> trop chouette ce moment !<break time="600ms"/></speak>',
        },
      ],
    },
  ],
};
